import ts from "typescript";

import type {ResolvedDependency, TokenSource} from "./resolver";

export interface AggregatorEntry {
    /** The decorated class itself - always an importable declaration. */
    classImport: Extract<TokenSource, {kind: "import"}>;
    dependencies: readonly ResolvedDependency[];
}

/**
 * Collects named imports across the whole generated file, deduping by (moduleSpecifier,
 * exportName) and aliasing local names on collision (e.g. two different `Repository` classes
 * from different modules).
 */
class ImportCollector {
    private readonly bySpecifier = new Map<string, Map<string, string>>();
    private readonly usedLocalNames = new Set<string>();

    add(moduleSpecifier: string, exportName: string): string {
        const byExport = this.bySpecifier.get(moduleSpecifier) ?? new Map<string, string>();
        this.bySpecifier.set(moduleSpecifier, byExport);

        const existing = byExport.get(exportName);
        if (existing) return existing;

        let localName = exportName;
        let suffix = 1;
        while (this.usedLocalNames.has(localName)) {
            localName = `${exportName}_${suffix++}`;
        }
        this.usedLocalNames.add(localName);
        byExport.set(exportName, localName);
        return localName;
    }

    toImportDeclarations(): ts.ImportDeclaration[] {
        const declarations: ts.ImportDeclaration[] = [];
        for (const [moduleSpecifier, byExport] of this.bySpecifier) {
            const specifiers = [...byExport.entries()].map(([exportName, localName]) =>
                ts.factory.createImportSpecifier(
                    false,
                    exportName === localName ? undefined : ts.factory.createIdentifier(exportName),
                    ts.factory.createIdentifier(localName),
                ),
            );
            declarations.push(
                ts.factory.createImportDeclaration(
                    undefined,
                    ts.factory.createImportClause(false, undefined, ts.factory.createNamedImports(specifiers)),
                    ts.factory.createStringLiteral(moduleSpecifier),
                ),
            );
        }
        return declarations;
    }
}

function tokenExpression(collector: ImportCollector, token: TokenSource): ts.Expression {
    if (token.kind === "literal") {
        return ts.factory.createStringLiteral(token.value);
    }
    const localName = collector.add(token.moduleSpecifier, token.exportName);
    return ts.factory.createIdentifier(localName);
}

function dependencyExpression(collector: ImportCollector, dependency: ResolvedDependency): ts.Expression {
    const tokenExpr = tokenExpression(collector, dependency.token);
    if (!dependency.optional) {
        return tokenExpr;
    }
    return ts.factory.createObjectLiteralExpression(
        [
            ts.factory.createPropertyAssignment("token", tokenExpr),
            ts.factory.createPropertyAssignment("optional", ts.factory.createTrue()),
        ],
        false,
    );
}

/**
 * Emits one aggregator file: imports + `defineDependencies(Target, [...])` calls, and nothing
 * else - no re-exports, to minimize its own contribution to any pre-existing circular-import
 * chains in the consuming app (see spec section 20).
 */
export function generateAggregatorSource(entries: readonly AggregatorEntry[], injectorModuleSpecifier: string): string {
    const collector = new ImportCollector();
    const defineDependenciesName = collector.add(injectorModuleSpecifier, "defineDependencies");

    const statements = entries.map(entry => {
        const classIdentifier = ts.factory.createIdentifier(
            collector.add(entry.classImport.moduleSpecifier, entry.classImport.exportName),
        );
        const dependencyArray = ts.factory.createArrayLiteralExpression(
            entry.dependencies.map(dep => dependencyExpression(collector, dep)),
            true,
        );
        return ts.factory.createExpressionStatement(
            ts.factory.createCallExpression(ts.factory.createIdentifier(defineDependenciesName), undefined, [
                classIdentifier,
                dependencyArray,
            ]),
        );
    });

    const importDeclarations = collector.toImportDeclarations();
    const sourceFile = ts.factory.createSourceFile(
        [...importDeclarations, ...statements],
        ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
        ts.NodeFlags.None,
    );

    const printer = ts.createPrinter({newLine: ts.NewLineKind.LineFeed});
    const header = "// AUTO-GENERATED by @nonna/compiler - do not edit by hand.\n";
    return header + printer.printFile(sourceFile);
}
