name: Release
on:
    workflow_dispatch:

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    release:
        runs-on: [ubuntu-latest]
        environment:
            name: release
        env:
            CI: false
            NODE_OPTIONS: --max-old-space-size=4096
            HUSKY_SKIP_HOOKS: 1
            HUSKY: 0
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Use node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "pnpm"

            - name: Install dependencies
              shell: bash
              run: pnpm install --frozen-lockfile

            - name: Setup environment variables
              run: echo "CURRENT_BRANCH=$(echo -n ${{github.head_ref || github.ref_name}})" >> $GITHUB_ENV

            - name: Building Packages
              run: pnpm build

            - name: Check code Style
              run: pnpm lint-format:fix

            - name: Execute Linter
              run: pnpm lint

            - name: Typescript Checks
              run: pnpm tsc

            - name: Start monorepo release
              id: start-monorepo-release
              uses: manusant/monorepo-release-start@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Write released packages to a manifest file
              run: echo '${{ steps.start-monorepo-release.outputs.releasedPackages }}' > release.manifest.json

            - name: Format Changesets
              run: pnpm changeset:format

            - name: Re-Install packages
              run: |
                  pnpm install

            - name: Finish monorepo release
              id: finish-monorepo-release
              if: steps.start-monorepo-release.outputs.released
              uses: manusant/monorepo-release-finish@v1
              with:
                  branch: ${{ env.CURRENT_BRANCH }}
                  releaseBranch: "main"
                  draft: false
                  push: true
                  version: ${{ steps.start-monorepo-release.outputs.version }}
                  previousPackages: ${{ steps.start-monorepo-release.outputs.oldPackages }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
