name: Test
on:
    workflow_dispatch:

    push:
        branches:
            - main

    pull_request_target:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
        paths:
            - "compiler/**"
            - "di/**"
            - "react/**"
            - "vue/**"
            - "svelte/**"
            - "web-components/**"
            - "stencil/**"
            - "vite-plugin/**"
            - "package.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: false

jobs:
    test:
        name: test (${{ matrix.name }})
        runs-on: [ubuntu-latest]
        if: (!github.event.pull_request || github.event.pull_request.draft == false)
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: di-framework
                      filter: '--filter="@nonnajs/compiler" --filter="@nonnajs/di"'
                    - name: web-support
                      filter: '--filter="@nonnajs/vite-plugin" --filter="@nonnajs/react" --filter="@nonnajs/vue" --filter="@nonnajs/svelte" --filter="@nonnajs/web-components" --filter="@nonnajs/stencil"'
        env:
            CI: true
            NODE_OPTIONS: --max-old-space-size=4096
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - name: Use node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: "pnpm"

            - name: Install dependencies
              shell: bash
              run: pnpm install --frozen-lockfile

            - name: Test with coverage
              run: |
                  pnpm turbo run test:coverage ${{ matrix.filter }}

            - name: Upload coverage to Codecov
              if: always()
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: nonnajs/nonna
                  fail_ci_if_error: false
                  verbose: true
                  flags: ${{ matrix.name }}

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: nonnajs/nonna
                  fail_ci_if_error: false
                  flags: ${{ matrix.name }}
